/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background:       '#080C14',
                surface:          '#0D1220',
                'surface-2':      '#111827',
                primary:          '#C6A85A',
                'primary-gold':   '#C6A85A',
                'soft-gold':      '#C6A85A',
                'gold-primary':   '#D4AF37',
                'gold-light':     '#F9E2AF',
                'gold-bright':    '#FFD966',
                'gold-dark':      '#9A7B2C',
                'gold-muted':     '#C6A85A',
                highlight:        '#F6E27A',
                bronze:           '#A89060',
                'text-primary':   '#E2E8F0',
                'text-secondary': '#8892A4',
                glass:            'rgba(8, 12, 20, 0.65)',
                'regime-compressed': '#10B981',
                'regime-normal':     '#3B82F6',
                'regime-stressed':   '#F59E0B',
                'regime-crisis':     '#EF4444',
                'regime-transition': '#8B5CF6',
            },
            fontFamily: {
                sans:    ['Outfit', 'system-ui', 'sans-serif'],
                heading: ['Outfit', 'system-ui', 'sans-serif'],
                mono:    ['JetBrains Mono', 'Fira Code', 'monospace'],
            },
            fontSize: {
                'market-mood':    ['52px', { lineHeight: '1',   fontWeight: '800', letterSpacing: '-0.03em' }],
                'market-mood-lg': ['72px', { lineHeight: '1',   fontWeight: '900', letterSpacing: '-0.04em' }],
                'card-header':    ['20px', { lineHeight: '1.2', fontWeight: '600' }],
                'price-lg':       ['24px', { lineHeight: '1',   fontWeight: '700', letterSpacing: '-0.02em', fontFamily: 'JetBrains Mono' }],
                'label':          ['10px', { letterSpacing: '0.12em', lineHeight: '1' }],
                'micro':          ['8px',  { letterSpacing: '0.15em', lineHeight: '1' }],
            },
            boxShadow: {
                'gold-glow':    '0 0 24px rgba(212, 175, 55, 0.25), 0 0 60px rgba(212, 175, 55, 0.08)',
                'gold-glow-sm': '0 0 12px rgba(212, 175, 55, 0.35)',
                'gold-glow-lg': '0 0 40px rgba(212, 175, 55, 0.35), 0 0 100px rgba(212, 175, 55, 0.12)',
                'green-glow':   '0 0 12px rgba(16, 185, 129, 0.4)',
                'amber-glow':   '0 0 12px rgba(245, 158, 11, 0.4)',
                'red-glow':     '0 0 12px rgba(239, 68, 68, 0.4)',
                'blue-glow':    '0 0 12px rgba(59, 130, 246, 0.4)',
                'purple-glow':  '0 0 12px rgba(139, 92, 246, 0.4)',
            },
            animation: {
                'pulse-slow':   'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'breathe-gold': 'gold-breathe 3s ease-in-out infinite',
                'ping-gold':    'ping-gold 1.5s ease-in-out infinite',
            },
            backgroundImage: {
                'gold-gradient': 'linear-gradient(135deg, #D4AF37 0%, #F9E2AF 50%, #9A7B2C 100%)',
                'gold-shine':    'linear-gradient(90deg, #D4AF37, #FFD966, #D4AF37)',
                'obsidian-radial': 'radial-gradient(ellipse at 50% 0%, rgba(212,175,55,0.08) 0%, transparent 70%)',
            },
        },
    },
    plugins: [],
}
